export const areas_list:
  | readonly [string, ...string[]]
  | [string, ...string[]] = [
  "Aisha Manzil",
  "Arambagh",
  "Askari (I–XIV)",
  "Bahadurabad",
  "Bahria Town Karachi",
  "Baldia Town",
  "Banaras Colony",
  "Bolton Market",
  "Buffer Zone",
  "Burns Road",
  "Chakiwara",
  "Civic Centre",
  "Clifton",
  "DHA City",
  "DHA",
  "Drigh Colony",
  "Essa Nagri",
  "Essa Mohalla",
  "FB Area (Blocks 1–22)",
  "Garden East",
  "Garden West",
  "Ghari Khata",
  "Golimar",
  "Gulberg",
  "Gulistan-e-Johar",
  "Gulshan-e-Iqbal",
  "Hyderi Market",
  "I.I. Chundrigar Road",
  "Jamshed Town",
  "Jodia Bazaar",
  "Kagzi Bazaar",
  "Karimabad",
  "KDA",
  "Keamari",
  "Kharadar",
  "Korangi",
  "Liaquatabad",
  "Light House",
  "M.A. Jinnah Road",
  "Mithadar",
  "Model Colony",
  "Nanakwara",
  "Nazimabad (Nos. 1–7)",
  "New Karachi",
  "North Karachi",
  "North Nazimabad Block A",
  "North Nazimabad Block B",
  "North Nazimabad Block C",
  "North Nazimabad Block D",
  "North Nazimabad Block E",
  "North Nazimabad Block F",
  "North Nazimabad Block G",
  "North Nazimabad Block H",
  "North Nazimabad Block I",
  "North Nazimabad Block J",
  "North Nazimabad Block K",
  "North Nazimabad Block L",
  "North Nazimabad Block M",
  "North Nazimabad Block N",
  "North Nazimabad Block O",
  "North Nazimabad Block P",
  "North Nazimabad Block Q",
  "North Nazimabad Block R",
  "North Nazimabad Block S",
  "North Nazimabad Block T",
  "North Nazimabad Block U",
  "North Nazimabad Block V",
  "North Nazimabad Block W",
  "North Nazimabad Block X",
  "North Nazimabad Block Y",
  "North Nazimabad Block Z",
  "Pan Mandi",
  "Pakistan Chowk",
  "Paposh Nagar",
  "Ranchore Line",
  "Saify Nagar",
  "Saddar",
  "Shabbirabad",
  "Shah Faisal Colony",
  "Shadman Town",
  "SITE Area",
  "Soldier Bazaar",
  "Surjani Town",
  "Tariq Road",
  "Teen Hatti",
  "Timber Market",
  "Water Pump",
  "Landa Bazar",
];

// const other_areas_list = [
//   "Saddar",
//   "Light House",
//   "Clifton",
//   "DHA",
//   "Gulshan-e-Iqbal",
//   "Gulistan-e-Johar",
//   "Korangi",
//   "Landhi",
//   "Malir",
//   "Model Colony",
//   "Shah Faisal Colony",
//   "North Nazimabad",
//   "Nazimabad",
//   "Liaquatabad",
//   "Federal B Area",
//   "Ancholi",
//   "Water Pump",
//   "Aisha Manzil",
//   "North Karachi",
//   "New Karachi",
//   "Orangi Town",
//   "Baldia Town",
//   "Lyari",
//   "Garden East",
//   "Garden West",
//   "PECHS",
//   "Bahadurabad",
//   "KDA",
//   "Karsaz",
//   "Cantt",
//   "Shireen Jinnah Colony",
//   "Manzoor Colony",
//   "Akhtar Colony",
//   "Mehmoodabad",
//   "Qayyumabad",
//   "Defence View",
//   "Azam Basti",
//   "Punjab Colony",
//   "Delhi Colony",
//   "Gizri",
//   "Karimabad",
//   "Yaseenabad",
//   "NIPA",
//   "Mosamyat",
//   "Sohrab Goth",
//   "Gulbahar",
//   "Safoora Chowrangi",
//   "Scheme 33",
//   "Abul Hassan Isphahani",
//   "Buffer Zone",
//   "Surjani Town",
//   "Khokhrapar",
//   "Saeedabad",
//   "Ibrahim Hyderi",
//   "Zaman Town",
//   "Sharafi Goth",
//   "Qasba Colony",
//   "Manghopir",
//   "Banaras",
//   "Nagan Chowrangi",
//   "Five Star Chowrangi",
//   "Hyderi",
//   "Paposh Nagar",
//   "Golimar",
//   "Kharadar",
//   "Mithadar",
//   "PIB Colony",
//   "Hasrat Mohani Colony",
//   "Jamshed Quarters",
//   "Essa Nagri",
//   "Gulshan-e-Maymar",
//   "Ahsanabad",
//   "Malir Cantt",
//   "Saudabad",
//   "Kala Board",
//   "Memon Goth",
//   "Steel Town",
//   "KDA Scheme 1",
//   "KDA Scheme 5",
//   "Garden",
//   "Soldier Bazaar",
//   "Lines Area",
//   "Cantt Station",
// ];
